
/***********************************************************/
/* Copyright (C) 2004 Avaya Inc.  All rights reserved.*/
/***********************************************************/

#ifndef SDBDEFS_H
#define SDBDEFS_H

#include "tsplatfm.h"
#include "ctisdbdefs.h"


#define          SDB_OPEN_CONNECTION 1
#define          SDB_OPEN_CONN_CONF 2
#define          SDB_CLOSE_CONNECTION 3
#define          SDB_CLOSE_CONN_CONF 4
#define          SDB_INSERT_OBJECT 5
#define          SDB_INSERT_OBJECT_CONF 6
#define          SDB_INSERT_ATTRIBUTE 7
#define          SDB_INSERT_ATTRIBUTE_CONF 8
#define          SDB_DELETE_OBJECT 9
#define          SDB_DELETE_OBJECT_CONF 10
#define          SDB_DELETE_ATTRIBUTE 11
#define          SDB_DELETE_ATTRIBUTE_CONF 12
#define          SDB_SELECT_OBJECT 13
#define          SDB_SELECT_OBJECT_CONF 14
#define          SDB_OPEN_CURSOR 15
#define          SDB_OPEN_CURSOR_CONF 16
#define          SDB_FETCH_CURSOR 17
#define          SDB_FETCH_CURSOR_CONF 18
#define          SDB_CLOSE_CURSOR 19
#define          SDB_CLOSE_CURSOR_CONF 20
#define          SDB_MODIFY_OBJECT 21
#define          SDB_MODIFY_OBJECT_CONF 22
#define          SDB_START_TRANS 23
#define          SDB_START_TRANS_CONF 24
#define          SDB_COMMIT_TRANS 25
#define          SDB_COMMIT_TRANS_CONF 26
#define          SDB_ROLLBACK_TRANS 27
#define          SDB_ROLLBACK_TRANS_CONF 28
#define          SDB_BACKUP_DATA_BASE 29
#define          SDB_BACKUP_DATA_BASE_CONF 30
#define          SDB_UPDATE_DATA_BASE 31
#define          SDB_UPDATE_DATA_BASE_CONF 32
#define          SDB_CREATE_TEMPLATE 33
#define          SDB_CREATE_TEMPLATE_CONF 34
#define          SDB_QUERY_VERSIONS 35
#define          SDB_QUERY_VERSIONS_CONF 36
#define          SDB_QUERY_FILES 37
#define          SDB_QUERY_FILES_CONF 38
#define          SDB_QUERY_ATTRIBUTES 39
#define          SDB_QUERY_ATTRIBUTES_CONF 40
#define          SDB_QUERY_STATUS 41
#define          SDB_QUERY_STATUS_CONF 42
#define          SDB_UNIVERSAL_FAILURE_CONF 43
#define          SDB_UNIVERSAL_FAILURE 44
#define          SDB_SELECT_KEY 45
#define          SDB_SELECT_KEY_CONF 46
#define          SDB_CONVERT_DATA_BASE 47
#define          SDB_CONVERT_DATA_BASE_CONF 48
#define          SDB_BACKUP_NDS_DATA_BASE 49
#define          SDB_BACKUP_NDS_DATA_BASE_CONF 50
#define          SDB_UPDATE_NDS_DATA_BASE 51
#define          SDB_UPDATE_NDS_DATA_BASE_CONF 52
#define          SDB_SET_SDB_LOG_OPTIONS 53
#define          SDB_SET_SDB_LOG_OPTIONS_CONF 54
#define          SDB_GET_SDB_LOG_OPTIONS 55
#define          SDB_GET_SDB_LOG_OPTIONS_CONF 56
#define          SDB_GET_CONNECTIONS 57
#define          SDB_GET_CONNECTIONS_CONF 58
#define          SDB_GET_ABOUT_INFO 59
#define          SDB_GET_ABOUT_CONF 60
#define          SDB_GET_ADMIN_INFO 61
#define          SDB_GET_ADMIN_INFO_CONF 62
#define          SDB_SET_ADMIN_INFO 63
#define          SDB_SET_ADMIN_INFO_CONF 64
#define          SDB_GET_TCP_INFO 65
#define          SDB_GET_TCP_INFO_CONF 66
#define          SDB_SET_TCP_INFO 67
#define          SDB_SET_TCP_INFO_CONF 68


#define   SDB_ORG	0x40000000
#define   SDB_ORGUNIT 0x20000000
#define   SDB_SIMPLE 0x10000000
#define   SDB_USER 0x00000001
#define   SDB_WORKTOP 0x00000002
#define   SDB_DEVICE 0x00000004
#define   SDB_DLIST 0x00000008
#define   SDB_TLINK 0x00000010
#define   SDB_TLIST 0x00000020
#define   SDB_OAMLIST 0x00000040
#define   SDB_TSERV 0x00000080
#define   SDB_DLIST_INDEX 0x00000100
#define   SDB_TLIST_INDEX 0x00000200
#define   SDB_OAMLIST_INDEX 0x00000400
#define   SDB_INDEX 0x00000800

#define    SDB_NON_FATAL 0x40
#define    SDB_OVERWRITE 0x20
#define    SDB_CONVERT_SIMPLE 0x10
#define    SDB_CONVERT_FLAT 0x08

#define    BTRV_TO_NDS 0x40
#define    BTRV_TO_UNIX 0x20

#define SDB_IP_HOST_NAME sdbIpHostName
#define SDB_IP_ADDRESS sdbIpAddress
#define NULL_ATTR nullAttr
#define LOGIN login
#define USER_NAME userName
#define USER_WKTP userWktp
#define DEV_DEV_LIST devDevList
#define CALL_DEV_LIST callDevList
#define CALL_CALL callCall
#define CALL_CTL_LIST callCtlList
#define ROUTING_LIST routingList
#define OAM_LIST oamList
#define SUPER_ADMIN_USER superAdminUser
#define ACL_USER aclUser
#define WKTP_NAME wktpName
#define WKTP_DEVICE wktpDevice
#define IPX_LAN_ADDR ipxLanAddr
#define IP_LAN_ADDR ipLanAddr
#define IP_NAME ipName
#define WKTP_DLIST wktpDlist
#define ACL_WKTP aclWktp
#define WKTP_INDEX wktpIndex
#define DEVICE_ID deviceId
#define DB_DEVICE_TYPE dbDeviceType
#define DEVICE_TLIST deviceTlist
#define LOCATION location
#define TELEPHONE_NO telephoneNo
#define ACL_DEVICE aclDevice
#define DEVICE_INDEX deviceIndex
#define DLIST_NAME dlistName
#define EXCEPT_LIST exceptList
#define DLIST_DEVICE dlistDevice
#define ACL_DLIST aclDlist
#define DLIST_INDEX dlistIndex
#define DLST_INDX dlstIndx
#define DEV_INDX devIndx
#define DLST_COMB dlstComb
#define TLINK_NAME tlinkName
#define SERVICE_TYPE serviceType
#define TLINK_INDEX tlinkIndex
#define TLIST_NAME tlistName
#define TLIST_LINKNM tlistLinknm
#define ACL_TLIST aclTlist
#define TLIST_INDEX tlistIndex
#define TLST_INDX tlstIndx
#define TLNK_INDX tlnkIndx
#define TLIST_COMB tlistComb
#define OAMLIST_NAME oamlistName
#define OAMLIST_LINKNM oamlistLinknm
#define ACL_OAMLIST aclOamlist
#define OAMLIST_INDEX oamlistIndex
#define OAMLST_INDX oamlstIndx
#define OAMLNK_INDX oamlnkIndx
#define OAMLIST_COMB oamlistComb
#define ORG_NAME orgName
#define ACL_ORG aclOrg
#define ORGUNIT_NAME orgunitName
#define ACL_ORGUNIT aclOrgunit
#define SDB_RET_SUCCESS sdbRetSuccess
#define SDB_RET_MORE_DATA sdbRetMoreData
#define SDB_RET_END_OF_FILE sdbRetEndOfFile
#define SDB_NORMAL sdbNormal
#define SDB_INITIALIZED sdbInitialized
#define SDB_INCONSISTENT sdbInconsistent
#define SDB_UNINITIALIZED sdbUninitialized
#define SDB_OLD_DATABASE sdbOldDatabase
#define SDB_SICK_DB_ENGINE sdbSickDbEngine
#define SDB_UNLOADING sdbUnloading
#define SDB_SHORT sdbShort
#define SDB_LONG sdbLong
#define SDB_STR sdbStr
#define SDB_BOOL sdbBool
#define SDB_STR_DN sdbStrDn
#define SDB_IPX sdbIpx
#define SDB_IP sdbIp
#define SDB_ACL sdbAcl
#define SDB_PHONE sdbPhone
#define SDB_GET_ALL sdbGetAll
#define SDB_GET_EQUAL sdbGetEqual
#define SDB_EXT_GET_EQUAL sdbExtGetEqual
#define SDB_GET_GROUP sdbGetGroup
#define SDB_EXT_GET_GROUP sdbExtGetGroup
#define SDB_CORRUPT_DICTNRY sdbCorruptDictnry
#define SDB_BAD_INDEX_FILE sdbBadIndexFile
#define SDB_MISSING_DICTIONARY sdbMissingDictionary
#define SDB_INVALID_STATE sdbInvalidState
#define SDB_INVALID_ATTRIBUTE_TYPE sdbInvalidAttributeType
#define SDB_TOO_MANY_ATTRIBUTES sdbTooManyAttributes
#define SDB_INVALID_FILE_TYPE sdbInvalidFileType
#define SDB_ATTR_NOT_IN_FILE sdbAttrNotInFile
#define SDB_INVALID_COMMAND sdbInvalidCommand
#define SDB_RECORD_NOT_FOUND sdbRecordNotFound
#define SDB_DATABASE_ERROR sdbDatabaseError
#define SDB_INCONSISTENT_DATABASE sdbInconsistentDatabase
#define SDB_INTERNAL_ERR sdbInternalErr
#define SDB_CONNECTION_TABLE_FULL sdbConnectionTableFull
#define SDB_INVALID_CONNECTION_ID sdbInvalidConnectionId
#define SDB_CONNECTION_NOT_ACTIVE sdbConnectionNotActive
#define SDB_INVALID_CONTEXT sdbInvalidContext
#define SDB_LOGIN_TABLE_FULL sdbLoginTableFull
#define SDB_FAILED_LOGIN sdbFailedLogin
#define SDB_NO_PERMISSIONS sdbNoPermissions
#define SDB_INVALID_DATA sdbInvalidData
#define SDB_MISSING_PRIMARY_KEY sdbMissingPrimaryKey
#define SDB_MANDATORY_ATTRIBUTE_MISSING sdbMandatoryAttributeMissing
#define SDB_INVALID_PRIMARY_KEY sdbInvalidPrimaryKey
#define SDB_INVALID_KEY sdbInvalidKey
#define SDB_DUPLICATE_KEY sdbDuplicateKey
#define SDB_MULTI_VAL_ATTR sdbMultiValAttr
#define SDB_NOT_MULTI_VALUED sdbNotMultiValued
#define SDB_INVALID_LIST_FILE sdbInvalidListFile
#define SDB_CURSOR_NOT_ACTIVE sdbCursorNotActive
#define SDB_CURSOR_SELECTION_NOT_SET sdbCursorSelectionNotSet
#define SDB_INVALID_CURSOR_OP sdbInvalidCursorOp
#define SDB_CURSOR_ALREADY_ACTIVE sdbCursorAlreadyActive
#define SDB_CURSOR_ACTIVE sdbCursorActive
#define SDB_OBJECT_NOT_ACCESSED sdbObjectNotAccessed
#define SDB_CONTENTION sdbContention
#define SDB_NO_MORE_DISK_SPACE sdbNoMoreDiskSpace
#define SDB_NO_MEMORY sdbNoMemory
#define SDB_MAX_OPEN_FILES_EXCEEDED sdbMaxOpenFilesExceeded
#define SDB_NO_ACTIVE_TRANSACTION sdbNoActiveTransaction
#define SDB_TRANSACTION_ALREADY_ACTIVE sdbTransactionAlreadyActive
#define SDB_TRANSACTION_ERROR sdbTransactionError
#define SDB_TRANSACTION_ABORTED sdbTransactionAborted
#define SDB_INVALID_OPCODE sdbInvalidOpcode
#define SDB_INVALID_RTN_CNT sdbInvalidRtnCnt
#define SDB_BUF_TOO_SMALL sdbBufTooSmall
#define SDB_KEY_SPECIFICATION sdbKeySpecification
#define SDB_ATTR_OVER_MAX sdbAttrOverMax
#define SDB_ATTR_UNDER_MIN sdbAttrUnderMin
#define SDB_DATA_TOO_LARGE sdbDataTooLarge
#define SDB_DOT_IN_KEY sdbDotInKey
#define SDB_WRITE_FAILED sdbWriteFailed
#define SDB_READ_FAILURE sdbReadFailure
#define SDB_FILE_NOT_PRESENT sdbFileNotPresent
#define SDB_NO_INFORM1_LINE sdbNoInform1Line
#define SDB_INVALID_ATTR_LIST sdbInvalidAttrList
#define SDB_INVALID_KEY_LIST sdbInvalidKeyList
#define SDB_INVALID_SELECT_LIST sdbInvalidSelectList
#define SDB_FOREIGN_KEY sdbForeignKey
#define SDB_OLD_DICTIONARY_FAILURE sdbOldDictionaryFailure
#define SDB_UPGRADE_ERR sdbUpgradeErr
#define SDB_FILE_ALREADY_EXISTS sdbFileAlreadyExists
#define SDB_OPEN_SDB_LOG_FAILED sdbOpenSdbLogFailed
#define SDB_WRITE_SDB_LOG_FAILED sdbWriteSdbLogFailed
#define SDB_FILE_OPEN_FAILURE sdbFileOpenFailure
#define SDB_QUERY_VERS_FAILED sdbQueryVersFailed
#define SDB_BA_BACKUP_FAILED sdbBaBackupFailed
#define SDB_SIMPLE_UPDATE_FAILED sdbSimpleUpdateFailed
#define SDB_QRY_FILES_FAILED sdbQryFilesFailed
#define SDB_QRY_ATTR_FAILED sdbQryAttrFailed
#define SDB_INVALID_INPUT_LINE sdbInvalidInputLine
#define SDB_CREATE_TMPLT_FAILED sdbCreateTmpltFailed
#define SDB_FLAT_UPDATE_FAILED sdbFlatUpdateFailed
#define SDB_CANT_MODIFY_MVATTR sdbCantModifyMvattr
#define SDB_DUPLICATE_FILE_NAMES sdbDuplicateFileNames
#define SDB_INVALID_VENDOR_LEN sdbInvalidVendorLen
#define SDB_INVALID_SERVICE_LEN sdbInvalidServiceLen
#define SDB_INVALID_SRV_TYPE sdbInvalidSrvType
#define SDB_INVALID_SRV_NAME_LEN sdbInvalidSrvNameLen
#define SDB_ALLOC_RESOURCE_ERR sdbAllocResourceErr
#define SDB_INIT_TSRV_PASSWD_ERR sdbInitTsrvPasswdErr
#define SDB_GET_TSRV_DEFAULT_ERR sdbGetTsrvDefaultErr
#define SDB_TSRV_LOADED sdbTsrvLoaded
#define SDB_SCHEMA_CHANGE_ERR sdbSchemaChangeErr
#define SDB_MUST_BE_CSTA sdbMustBeCsta
#define SDB_INVALID_FILE_NM sdbInvalidFileNm
#define SDB_INVALID_FILE_FORMAT sdbInvalidFileFormat
#define SDB_LAST_ADMIN_USER sdbLastAdminUser
#define SDB_MIXED_VERSION_NUMBERS sdbMixedVersionNumbers
#define SDB_LAST_ERR sdbLastErr

#define SDB_BTRIEVE 0x40
#define SDB_NDS	0x20

#endif
